---

stages:
- validate
- version
- publish

include:
- local: templates/module-validate.yml
- local: templates/generate-version.yml
- local: templates/module-publish.yml

workflow:
  name: '$PIPELINE_NAME'
  rules:
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
    when: always
    variables:
      PIPELINE_NAME: 'Module Publish Pipeline Triggered by Push Commit'
  - if: $CI_COMMIT_TAG
    when: always
    variables:
      PIPELINE_NAME: 'Module Publish Pipeline Triggered by Git Tag'
  - when: never

variables:
  # set build variables as to make jobs more flexible
  TERRAFORM_MODULE_DIR: "${CI_PROJECT_DIR}"    # The relative path to the root directory of the Terraform project.
  TERRAFORM_MODULE_NAME: "${CI_PROJECT_NAME}"  # The name of your Terraform module, must not have any spaces or underscores (will be translated to hyphens).
  TERRAFORM_MODULE_SYSTEM: "" # The system or provider your Terraform module targets (ex. local, aws, google).
  TERRAFORM_MODULE_VERSION: "" # The version - it's recommended to follow SemVer for Terraform Module Versioning.
  
  GITCLIFF_VERSION: '2.8.0'
  GITCLIFF_TARBALL: 'git-cliff-${GITCLIFF_VERSION}-x86_64-unknown-linux-gnu.tar.gz'
  GITCLIFF_GITHUB: 'https://github.com/orhun/git-cliff/releases/download/v${GITCLIFF_VERSION}/${GITCLIFF_TARBALL}'

module-validate:
  extends: .module-validate

generate-version:
  extends: .generate-version

module-publish:
  needs:
    - job: generate-version
      artifacts: true
  extends: .module-publish
